apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
  namespace: network-part1
spec:
  type: NodePort
  selector:
    app: nettools
  ports:
    - port: 80
      name: nginx-port
      targetPort: 80
      nodePort: 30007
    - port: 8080
      name: multitool-port
      targetPort: 1180
      nodePort: 30008
